package common.net;

public enum MessageType {
    // Xác thực
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    SIGNOUT_REQUEST,
    //Chat single
    CREATE_SINGLE_CONVERSATION_REQUEST,
    CREATE_SINGLE_CONVERSATION_RESPONSE,
    SEND_SINGLE_CHAT_MESSAGE_REQUEST,
    SEND_SINGLE_CHAT_MESSAGE_RESPONSE,
    //Information
    GET_LIST_SINGLE_USER_REQUEST,
    GET_LIST_SINGLE_USER_RESPOND,
    GET_LIST_GROUP_REQUEST,
    GET_LIST_GROUP_RESPOND,

    //Check
    CHECK_EXITS_USER_ID_REQUEST,
    CHECK_EXITS_USER_ID_RESPOND,

    //Chat group
    CREATE_GROUP_CONVERSATION_REQUEST,
    CREATE_GROUP_CONVERSATION_RESPOND,
    SEND_GROUP_CHAT_MESSAGE_REQUEST,
    SEND_GROUP_CHAT_MESSAGE_RESPONSE,
}
