package common.net;

public enum MessageType {
    // Xác thực
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    SIGNOUT_REQUEST,
    //Chat
    CREATE_SINGLE_CONVERSATION_REQUEST,
    CREATE_SINGLE_CONVERSATION_RESPONSE,
    SEND_SINGLE_CHAT_MESSAGE_REQUEST,
    SEND_SINGLE_CHAT_MESSAGE_RESPONSE,
    //Information
    GET_LIST_SINGLE_USER_REQUEST,
    GET_LIST_SINGLE_USER_RESPOND,
    GET_LIST_GROUP_REQUEST,
    GET_LIST_GROUP_RESPOND,
}
